version: "3.9"

services:
  web_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_api_application
    ports:
      - "5001:443"
    depends_on:
      - sql

  sql:
    image: "mcr.microsoft.com/azure-sql-edge"
    container_name: azure-sql-edge
    ports:
      - "1434:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Phuduc@30072001
